require_relative "Utilities"
require 'set'

def problem2(max)
  #Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

  sum = 0
  fib_up_to( max ) do |x| 
      sum = sum + x if x.even?
  end
  sum
end 

p problem2 4000000